CREATE TABLE `pointTransactions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`amount` int NOT NULL,
	`balanceAfter` int NOT NULL,
	`type` enum('EARNED','SPENT','BONUS','REFUND','EXPIRED','ADJUSTMENT') NOT NULL,
	`sourceType` enum('PROJECT_COMPLETE','TASK_COMPLETE','STREAK_BONUS','LEVEL_UP','ACHIEVEMENT','REDEMPTION','ADMIN','REFERRAL'),
	`sourceId` int,
	`redemptionId` int,
	`description` varchar(200),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `pointTransactions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `rewardRedemptions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`rewardId` int NOT NULL,
	`pointsSpent` int NOT NULL,
	`status` enum('PENDING','PROCESSING','COMPLETED','SHIPPED','DELIVERED','CANCELED','REFUNDED') DEFAULT 'PENDING',
	`couponCode` varchar(50),
	`couponUsed` boolean DEFAULT false,
	`couponUsedAt` timestamp,
	`shippingName` varchar(200),
	`shippingAddress` text,
	`shippingCity` varchar(100),
	`shippingState` varchar(50),
	`shippingZip` varchar(20),
	`shippingCountry` varchar(50) DEFAULT 'BR',
	`trackingCode` varchar(100),
	`notes` text,
	`redeemedAt` timestamp NOT NULL DEFAULT (now()),
	`processedAt` timestamp,
	`completedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `rewardRedemptions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `rewards` (
	`id` int AUTO_INCREMENT NOT NULL,
	`code` varchar(50) NOT NULL,
	`name` varchar(200) NOT NULL,
	`description` text,
	`type` enum('DISCOUNT','PRODUCT','FEATURE','BADGE') NOT NULL,
	`pointsCost` int NOT NULL,
	`discountType` enum('PERCENTAGE','FIXED'),
	`discountValue` int,
	`discountAppliesTo` enum('PRO','TEAM','ANY'),
	`productSku` varchar(50),
	`productImageUrl` varchar(500),
	`productPrice` int,
	`shippingIncluded` boolean DEFAULT false,
	`stock` int,
	`maxPerUser` int DEFAULT 1,
	`isActive` boolean DEFAULT true,
	`isPremiumOnly` boolean DEFAULT false,
	`validFrom` timestamp,
	`validUntil` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `rewards_id` PRIMARY KEY(`id`),
	CONSTRAINT `rewards_code_unique` UNIQUE(`code`)
);
--> statement-breakpoint
CREATE TABLE `storeOrderItems` (
	`id` int AUTO_INCREMENT NOT NULL,
	`orderId` int NOT NULL,
	`productId` int NOT NULL,
	`productName` varchar(200) NOT NULL,
	`productSku` varchar(50) NOT NULL,
	`quantity` int NOT NULL,
	`priceInCents` int NOT NULL,
	`totalInCents` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `storeOrderItems_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `storeOrders` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`orderNumber` varchar(50) NOT NULL,
	`status` enum('PENDING','PAID','PROCESSING','SHIPPED','DELIVERED','CANCELED','REFUNDED') DEFAULT 'PENDING',
	`paymentMethod` enum('STRIPE','POINTS','MIXED') DEFAULT 'STRIPE',
	`subtotalInCents` int NOT NULL,
	`shippingInCents` int DEFAULT 0,
	`discountInCents` int DEFAULT 0,
	`totalInCents` int NOT NULL,
	`pointsUsed` int DEFAULT 0,
	`stripePaymentIntentId` varchar(255),
	`couponCode` varchar(50),
	`shippingName` varchar(200),
	`shippingEmail` varchar(320),
	`shippingPhone` varchar(50),
	`shippingAddress` text,
	`shippingCity` varchar(100),
	`shippingState` varchar(50),
	`shippingZip` varchar(20),
	`shippingCountry` varchar(50) DEFAULT 'BR',
	`trackingCode` varchar(100),
	`shippedAt` timestamp,
	`deliveredAt` timestamp,
	`customerNotes` text,
	`internalNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `storeOrders_id` PRIMARY KEY(`id`),
	CONSTRAINT `storeOrders_orderNumber_unique` UNIQUE(`orderNumber`)
);
--> statement-breakpoint
CREATE TABLE `storeProducts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`sku` varchar(50) NOT NULL,
	`name` varchar(200) NOT NULL,
	`description` text,
	`longDescription` text,
	`category` enum('PLANNER','TIMER','FIDGET','ORGANIZER','BOOK','ACCESSORY','KIT') DEFAULT 'ACCESSORY',
	`priceInCents` int NOT NULL,
	`compareAtPriceInCents` int,
	`pointsPrice` int,
	`pointsOnly` boolean DEFAULT false,
	`imageUrl` varchar(500),
	`images` json,
	`stock` int DEFAULT 0,
	`lowStockThreshold` int DEFAULT 5,
	`trackInventory` boolean DEFAULT true,
	`weight` int,
	`dimensions` json,
	`freeShipping` boolean DEFAULT false,
	`isActive` boolean DEFAULT true,
	`isFeatured` boolean DEFAULT false,
	`slug` varchar(200),
	`metaTitle` varchar(200),
	`metaDescription` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `storeProducts_id` PRIMARY KEY(`id`),
	CONSTRAINT `storeProducts_sku_unique` UNIQUE(`sku`)
);
