import { useState } from "react";
import { motion } from "framer-motion";
import { BookOpen, Sparkles, Edit2, Save, X } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "sonner";

interface WhereILeftOffProps {
  projectId?: number;
}

export default function WhereILeftOff({ projectId }: WhereILeftOffProps) {
  const { data: lastNote, isLoading, refetch } = trpc.sessionNotes.getLastNote.useQuery();
  const saveNote = trpc.sessionNotes.saveNote.useMutation({
    onSuccess: () => {
      refetch();
      toast.success("Nota salva com sucesso!");
      setIsEditing(false);
    },
  });
  const generateSummary = trpc.sessionNotes.generateAutoSummary.useMutation({
    onSuccess: () => {
      refetch();
      toast.success("Resumo gerado pela IA!");
    },
  });

  const [isEditing, setIsEditing] = useState(false);
  const [noteText, setNoteText] = useState("");

  if (isLoading) {
    return (
      <div className="bg-card rounded-xl p-6 border animate-pulse">
        <div className="h-6 bg-muted rounded w-1/3 mb-4" />
        <div className="h-20 bg-muted rounded" />
      </div>
    );
  }

  const handleSave = () => {
    if (!noteText.trim()) {
      toast.error("A nota não pode estar vazia");
      return;
    }

    saveNote.mutate({
      note: noteText,
      projectId,
      isAutoGenerated: false,
    });
  };

  const handleGenerateAI = () => {
    if (!projectId) {
      toast.error("Selecione um projeto primeiro");
      return;
    }

    generateSummary.mutate({ projectId });
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      className="bg-gradient-to-br from-primary/5 to-primary/10 rounded-xl p-6 border border-primary/20"
    >
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center gap-2">
          <BookOpen className="w-5 h-5 text-primary" />
          <h3 className="font-semibold text-lg">Onde Parei</h3>
        </div>

        {!isEditing && (
          <div className="flex gap-2">
            {projectId && (
              <Button
                variant="ghost"
                size="sm"
                onClick={handleGenerateAI}
                disabled={generateSummary.isPending}
                className="gap-2"
              >
                <Sparkles className="w-4 h-4" />
                {generateSummary.isPending ? "Gerando..." : "IA"}
              </Button>
            )}
            <Button
              variant="ghost"
              size="sm"
              onClick={() => {
                setIsEditing(true);
                setNoteText(lastNote?.note || "");
              }}
              className="gap-2"
            >
              <Edit2 className="w-4 h-4" />
              Editar
            </Button>
          </div>
        )}
      </div>

      {isEditing ? (
        <div className="space-y-3">
          <Textarea
            value={noteText}
            onChange={(e) => setNoteText(e.target.value)}
            placeholder="Descreva onde você parou e o que precisa fazer a seguir..."
            className="min-h-[100px] bg-background"
            maxLength={500}
          />
          <div className="flex items-center justify-between">
            <span className="text-xs text-muted-foreground">
              {noteText.length}/500 caracteres
            </span>
            <div className="flex gap-2">
              <Button
                variant="ghost"
                size="sm"
                onClick={() => {
                  setIsEditing(false);
                  setNoteText("");
                }}
              >
                <X className="w-4 h-4 mr-1" />
                Cancelar
              </Button>
              <Button
                size="sm"
                onClick={handleSave}
                disabled={saveNote.isPending}
              >
                <Save className="w-4 h-4 mr-1" />
                {saveNote.isPending ? "Salvando..." : "Salvar"}
              </Button>
            </div>
          </div>
        </div>
      ) : lastNote ? (
        <div className="space-y-2">
          <p className="text-sm text-foreground leading-relaxed">
            {lastNote.note}
          </p>
          {lastNote.projectName && (
            <p className="text-xs text-muted-foreground">
              Projeto: <span className="font-medium">{lastNote.projectName}</span>
            </p>
          )}
          {lastNote.isAutoGenerated && (
            <div className="flex items-center gap-1 text-xs text-primary">
              <Sparkles className="w-3 h-3" />
              <span>Gerado automaticamente pela IA</span>
            </div>
          )}
        </div>
      ) : (
        <div className="text-center py-6">
          <p className="text-sm text-muted-foreground mb-3">
            Ainda não há anotações. Clique em "Editar" para começar.
          </p>
          {projectId && (
            <Button
              variant="outline"
              size="sm"
              onClick={handleGenerateAI}
              disabled={generateSummary.isPending}
              className="gap-2"
            >
              <Sparkles className="w-4 h-4" />
              {generateSummary.isPending ? "Gerando..." : "Gerar com IA"}
            </Button>
          )}
        </div>
      )}
    </motion.div>
  );
}
